### ISSUE TITLE
Can't run on win10

### ISSUE THREAD

**Issue by SilentWarrior1** [Nikait/ni_GuiBomber#2]
exe can't run on win10 ltsc 1809.
https://i.imgur.com/y1DSn2e.png

**Comment by Nikait** [comment]
Please install python 3.7 and higher on windows.  Next, enter the pip install pyinstaller command.  Next, download the py file from this repository and in the console go to this and run the command pyinstaller -w -F ni_GuiBomber.py.  Now go to the dist directory and there will be a compiled .exe file
